vim.o.expandtab = true
vim.o.tabstop = 4
vim.o.shiftwidth = 4
vim.o.number = true
vim.o.relativenumber = false
vim.o.showmode = false
vim.o.wrap = false
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.signcolumn = 'number'
vim.o.title = true
vim.o.spell = true
vim.o.mouse = 'a'
vim.o.hidden = true
vim.o.termguicolors = true
vim.o.splitright = true
vim.o.list = true
vim.o.listchars = 'tab:▸ ,trail:·'
vim.o.scrolloff = 8
vim.o.sidescrolloff = 8
vim.o.undofile = true
vim.o.wildmode= 'longest:full,full'
vim.o.clipboard = 'unnamedplus'
vim.o.confirm = true
vim.o.backup = true
vim.o.backupdir = vim.fn.stdpath 'data' .. '/backup//'
vim.o.updatetime = 250
vim.o.redrawtime = 1000
vim.o.fillchars = 'eob: '
